databases:
  - name: teatro-db
    databaseName: teatro_ecommerce
    user: teatro_user

services:
  - type: web
    name: teatro-app
    runtime: python
    buildCommand: "pip install -r app/requirements.txt"
    startCommand: "cd app && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: teatro-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: teatro-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: teatro-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: teatro-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: teatro-db
          property: database
      - key: DB_PORT
        value: 5432
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USE_SSL
        value: False
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
